"""added new db vocalbulary

Revision ID: 451d41838c6a
Revises: e1a4f7dc9671
Create Date: 2026-04-04 16:57:33.628509

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '451d41838c6a'
down_revision: Union[str, Sequence[str], None] = 'e1a4f7dc9671'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
