"""changed password from string to Binary

Revision ID: 5f100bfdd6e8
Revises: 795d49ca0b27
Create Date: 2026-03-30 18:34:23.117141

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5f100bfdd6e8'
down_revision: Union[str, Sequence[str], None] = '795d49ca0b27'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # batch_alter_table is used here for SQLite compatibility.
    # SQLite does not support ALTER COLUMN directly, so Alembic works around
    # this by recreating the table with the new column type behind the scenes.
    with op.batch_alter_table('users') as batch_op:
        batch_op.alter_column('password',
                        existing_type=sa.String(),
                        type_=sa.LargeBinary(),
                        postgresql_using='password::bytea')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users') as batch_op:
        batch_op.alter_column('password',
                   existing_type=sa.LargeBinary(),
                   type_=sa.VARCHAR(length=100),
                   existing_nullable=False)
    op.drop_table('stories')
    # ### end Alembic commands ###
